from .dot import dot
from .matmul import matmul
from .vdot import vdot
from .inner import inner
from .outer import outer
from .tensordot import tensordot
from .einsum import einsum
from .inv import inv
from .pinv import pinv
from .solve import solve
from .lstsq import lstsq
from .det import det
from .trace import trace
from .norm import norm
from .cond import cond
from .matrix_power import matrix_power
from .kron import kron
from .diagonal import diagonal
from .cholesky import cholesky
from .qr import qr
