from .mean import mean
from .median import median
from .std import std
from .var import var
from .average import average
from .percentile import percentile
from .quantile import quantile
from .ptp import ptp
from .bincount import bincount
from .hist import hist
from .cov import cov
from .corrcoef import corrcoef
from .correlate import correlate
from .digitize import digitize
