from .average import average
from .bincount import bincount
from .corrcoef import corrcoef
from .correlate import correlate
from .cov import cov
from .digitize import digitize
from .hist import hist
from .hist2d import hist2d
from .mean import mean
from .median import median
from .percentile import percentile
from .ptp import ptp
from .std import std
from .var import var
